# Generated by Django 4.0.6 on 2022-07-05 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accompli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_participation_debut', models.DateField(verbose_name='date début de participation')),
                ('date_participation_fin', models.DateField(verbose_name='date fin début de participation')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('num', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='numéro de commune')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255, verbose_name='theme')),
                ('date_debut', models.DateField(verbose_name='date début')),
                ('date_fin', models.DateField(verbose_name='date fin')),
                ('duree_tache', models.IntegerField(verbose_name='durée du projet  en jours')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nom', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('date_plus_tot', models.DateField(verbose_name='date au plus tot')),
                ('date_plus_tard', models.DateField(verbose_name='date au plus tard')),
                ('duree_tache', models.IntegerField(verbose_name='durée de la tache en jours')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.projet', verbose_name='projet')),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('prenom', models.CharField(max_length=255, verbose_name='prénom')),
                ('competence', models.CharField(choices=[('aucune', 'aucune'), ('anglais', 'anglais'), ('allemand', 'allemand'), ('espagnol', 'espagnol'), ('portugais', 'portuguais'), ('arabe', 'arabe'), ('russe', 'russe'), ('chinois', 'chinois'), ('autre', 'autre')], default='aucune', max_length=9)),
                ('salaire', models.FloatField()),
                ('isChef', models.BooleanField(default=False, verbose_name='est chef de division')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.commune', verbose_name='commune')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.division', verbose_name='division')),
                ('taches', models.ManyToManyField(through='planner.Accompli', to='planner.tache', verbose_name='tâches')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.salarie', verbose_name='chef de projet'),
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('num', models.CharField(help_text='le n°1 de essonne est 91', max_length=2, primary_key=True, serialize=False, verbose_name='numéro de département')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.region', verbose_name='région')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.departement', verbose_name='département'),
        ),
        migrations.AddField(
            model_name='accompli',
            name='salarie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.salarie', verbose_name='salarié'),
        ),
        migrations.AddField(
            model_name='accompli',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.tache', verbose_name='tâche'),
        ),
    ]
